# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  priv_key:
    secure: rqCcs028DoeGjp9hfDajOu5L68/juyrFXD43oxiPl9buKOC2TNFrEKyNJ6vAU8vEmAx78SKDWSA9znCtN7Jc/6tkoNT3MpIL6H6mPld2/yC+cZpVDA85WSV6jh+a9yGfLcQFZQvbhxdfTitFT61WRCTnTU9tA8QKX1og8E9DvScoX61apDQ86kH/Cf3G7/zgP0QO1a+VNcYHCacI60cm0w2QQgnDqy4l7YdLankKA5e31l7WeHJoNfLyXEYnNcH3K4aP+3ydktpSnXqUSRF/t0xQRxvgNzT33uTHkTFNVgehXWjy5tH/4ySX2NepYTp/gmTaIDczRb/HcvzVBaYy8hiVdx0LMKDZ53/OhIT9hqsn35Sm5yAz2wiW3RQ+tcVMAYM+PCWPn/xfcAygNzaC6GodwuO0yVaElLc06io9vBQR7DQomDaqtwtJTfnTuP90busFAMcqw9NUQkTyFwJnN7/wNLnj2PMQ9cKxM8qo9aFPETsbYbyHysHAUZuN1ymopKZRb77UJ8W95rx2kTNl7B8wMffSwFKhZTcgY1bct+pBWicp1ZXgvZsNtSpEVxeFLbbNMOuWbkP22PzgnlcxhlsCCztUI2X4giHh+VFGQ8r4GoIPkJY+J5RxsWkBEz3X46mJSkWaIbR2Hlyd1JFIA1ZTaUzhn1XE7kqdC3MLEJyNhOsgcEXcOEuPs5t921rcBQzk+is/emcK/7qCPGFGvvd/YexV9JLBu1FaBjnFWoiurel74jdYCaB//uexyivVMEJl5Fzl5EXqTD74s6Qn26CByd1U7DL/JIcZ3SmSDfxqlSk45U9vpZWwoBrFQ6tVg+G1pQdzNyjx6F+dzEqqphjaAtDF2sfh+xNXZhAxwVFYxrvi7GxWxaMrB7z9e/THIw5EDdVfoMl5X5GLDIYWVg2aC6NtQn8YQPYaXaQ/mGc6LcVKo+MhlCMtvig385iuaTDvmZWMgIAs4nKyOOBjKZWs72WCXd3EA55xTKFzQK3QwJx2ajUyYNduMFYgFeBAMIvsavZjZfsYHNI0SWIo0bPGCm1mdIkTCObRU/eNZRwBnDpI4ykeTyin9mZGDuLnRq54iYOVHuqvkeaOrhvNpLusHBtYWSzL5fU6+nOSTXGKNQho+AL0ZCGWrQ+n5KnT+3CyUarIwyw8jFsgfgR+ujQ8Bqm8qpBmlzS1qaPNaq/KfefM9+9tw0fMLrt+Cw29wVg+CAvbVEQmH2qbPTVGpUqzh8+OB80EC9n/x1CzAx9DU8Qbo9f0Glc7PHqgOu5Sk4ju/PjDvndY9BiywuO03PwRxfCyG/TLE1JQ9UuEw9QhF1uDLzN9rSa5NnEFJEJn/0WfSkJV4CAqmEtaaaWJA4qJL0gjq5/LBfhmx/oA/N3sGUIchf0yU02zKV8EqYbVy+wDSplnM3E8iNqfpHklxvHYz/7IBSMBGJ4fYuOfkozE2iyxgs81L31DHHHS7uAqEuIcVrCJaJl+eDz5ietrGBixR/uKznSHYxDAGNEwRyLdoNOg0DG40SH85T7i0u9jeqZkhyoiMfG7uQFzcvvA9to64N91mFuGYWh9WHViXtGRrq59xMXTkVOcVWWbQljiRakDP5TqcFBamMr6LNMp49cxZfyUBe3xWJxIMEVxA0jojbXz8sv9rYhaXxH9rw2/uK44xlCKG1aTVIq4yKBaSZBXqpJNyDhannjI/500xNoapL6IO/ttCBmhkMFhbdNW6n88gEkEUIUSf76MPDvbkbjLmTUnfeWd7CYCuzWIu3a9r5xJAjioN0BvEU2ooJGxUTOCKphQrazvuYYSMet1yBkf2LlaOgXn9rvuylYNTWIk/Dparx5cIlqll+aKe958GyHdwNkp6tNyztneDmW6UZF12mXjmwh6ogMh4Ru2ssYfoCORpzwpIvSD8uo9EjFG52FCWEs64AixlRRuACZ5/aUouCThun1Rh6Mzmtz/Y1GXaPEz7a8O03HG0XkKpR35bvACf170OtsDEZqTyRkeSlSdY0i9plRaadS0xEquDiuYnGNkUDjSZ8jfGs0ZPGMzOKsqVSwWhM7AIIQCFVKIt8Qmmqz1Y5V61uW4L8XI+2QxoHcHKgd5edZydZ4NkmTpowBCklxKeDHKRKMiMgeeW/aatlgKI1iPHYluCi06I5qDmkWGNzxbz1Nw1V7i2GbTrJ+n6rDl2fvjkvDbncWoaedHTCo5bHQPBPYDj7cZmV3TnBW3Llv1xw+5KWytTt2dpGVRE/myshHc1AAgPH82HjOPSmpPbXC9RIhsph0K9b5TMAcqYGyRcg4n3xz+x0p5JTClHIBHNU9FU4cH4vqOPdpSW1T3BmlLXi9Ymg3OUwUTG4x8d//tnrGQ1Q1RzoGt+FGYJf+dLbzpueyqAlrtmh/aScaeiKVwGs9yDcOoltzCXbgO8oXGH1atMEldRe2VrsyLxvoKRPQ+ktKBDi4GDa42SlRznewV1lni9Mq6xRtJhl6aQdNqu/lrdHjH2jCUxV9P4z79WutltHDq8UmFabVltflBsxtMilIZvVIRfQqH2lnCThfmomt1Zq4IoUH4/EDaBcu0bvPs/n6rnxzH7EuOAtchhrEZQblyQzhMvWKkPbR/iqbNsFEiq7F4HVX+/ZdHQ6Uu2in7ukCN5ILqusjwL+ZNb/9EYzVz9zsUQ+ZfLY2OH2492VrN+lHjmt7XzDehU7ncTM+dxMt0quD52govG0/7oUWzE+6BJsNOS6rLz4T54ADlS6wMxEN7bYkqhDHPredU/R15ph0ijIe+egvxVvXzk29gKnTm3+muYyFUVfWWblAgdbFWw8skubk/I6Np3pX0PbeXPTDvxsWAzFoBoiMKORZ76+GThCvzc6dNGX6Yr802RVNnmENXYhvoWJhZ6C85LGRbKWcT2vkd/To8m5TSar0+c6RA4Ism4reV2hP8TxC0FIYMCDlwl9tlnQlELdQ5rT+JNKn0SSPoBaRKiDOCIGFwjX+k6HAfuVBS0+5uqTi2pjvTldBcxmOx3pMcAGQJAbmOCjbkOPdv3SXICqE+EnqRWwkevYCDqtxtRXXKohXOCQKcZjP31i1v8DI4W4y22PXTT8hrmxJVh28ZCKXOFM7LCLm6up+yKB9Doj9TW8TIZt/VIoIXa2ArozkplenylLQchAcHXjD+9Z7l2IF2mtt8BakCGLu5DvpUMiNZqyuZWUI3vbekfFaFCMSkdqmh9xmTvEF6aHlTLi3AWbgK9Z1elOuq/UsMo2wVIM/XmbL3DhvVGzaTVjZ023MQ3YtbItZnv8uyyMr3KUFchMYp0aLWJ4/ZOpiiAbMv5omho2DeVS3KNmXedfzELcbpVSiryXbJXa6/V/91GOHwr1EnDwvPt2iW51C/J35ZANcix98504cRZsHJ+SYg
  global:
    GITHUB_USER_PASSWORD:
      secure: E+YdBdg3dqm5vZl25Ug5KYfa2M5I3/LdtVR/UtV9HZT1EEkrsQPFd9MQdxg/pbtE

  matrix:
    - TYPE: Release
    - TYPE: Debug

init:
  - cmd: >-
      cd c:\users\appveyor

      echo "-----BEGIN OPENSSH PRIVATE KEY-----" > id_rsa

      echo "${priv_key}" | tr " " "\n" >> id_rsa

      echo "-----END OPENSSH PRIVATE KEY-----" >> id_rsa

      ls

      chmod 700 id_rsa

      eval "$(ssh-agent -s)"

      ssh-add ~/id_rsa

      ssh -T git@github.com

install:
  # Python 3
  - cmd: set PATH=C:\Python-x64;C:\Python-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

build_script:
  - cmd: cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=%TYPE%
  - cmd: cmake --build _builds --config %TYPE%

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - /^pr\..*/