# Windows (https://github.com/travis-ci-tester/toolchain-table)

image:
  - Visual Studio 2022
  - macOS-Monterey
environment:
  GITHUB_USER_PASSWORD:
    secure: M/8NPK94UTSRMO1reIluuYJsqiLCZS5jH5E+Lqm9+126+QLDd1fuQF9QZP7vJy+b
  matrix:
    - TYPE: Release
    #- TYPE: Debug

install:
  # Python 3
  - cmd: set PATH=C:\Python-x64;C:\Python-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests
  - cmd: pip install gitpython

build_script:
  - cmd: cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=%TYPE%
  - cmd: cmake --build _builds --config %TYPE%

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - /^pr\..*/