# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  priv_key:
    secure: rqCcs028DoeGjp9hfDajOreIofyN/M8l8AVHCVxMoCvhyhFvWnz20Nwv87b3Bmabc76XNX4OM87DTMY01Q98Gj0HSzNp8Vub8nRaVJQK4OkV6UhcDL9DDAnOSNidWksPvzlW0Lm+TlSSlSnRAVUQTSLoovlXXQhSMavB0WaUXVItAXntMTej0TbWKvpAAa/ch4TS+AN3yTpWn3IEiAtvje2l6mG+jHGsllHoM/paNiHeiQ63d79YLPgfjIjbuURwIUlimF8tk/uUX8sNjUg6nwNU8sgvk/c01BJtsi1uJvpu4EatPQ7RSlKlx5WByI2eUjDdhLDHVTojmpdRfTQE62djut4PJyWowMnddnFXkswappbP7Bkhk1ZiOdGwv+h54t9a4eZ+jOTfU2m1VFM8xXuRf3vwCh05YVK7N2fJ2cIEHtpg3o3p+jGHf8a+W9fT4jEHhVdy1faHSyDvtExaL2U5AqoitN9FmCODc9fQwjFMjaLVIaJTHTPCG8lLHad9In/pjr4MnwNLL5mVHW3djmHblQR3BG7Xu3jxHLQC6QG6hodNncgF/tADZPYA1JxZGWhkGF5+RqvxMJgLbnxNt33NqWNJSb51XJhE+DKP/qbQL1tsupn6s//r/UiigHdxfDFgsG2+JKB6rQhi5ELnpStaMK6vgWMdCVjAkPjtFerLRJ566fFWXpSIpYhbllM3M+yKvyEdi8dV3DoHQEeTPxyp5qpe9hSaAAS4eYMYnKohxxD5W//+/r5ENerpGFsjNpOR5+ObO/9QSlcOeLTbGxPNMvpaFw8leVm0Z1jrpVPRRc8rIcATj59FtpzKUWhSG2hWGTRYwC8dagNjRX8GyrXLdx15NUDvQgew7ki4k9CzOoR0/QKh9mSMNFI1sev7hMIHLUwtP+zQKTG1rNAHDMbj9IDYIkH2Ln13JXLq8Y0tIW6dO1Ztw8R1IFJPM5vO6rjkmkBi9CUqOsdmaL/vos9hgjWAf3JnnlI8+Mc8tXGb96o1ld5Lfjt26Wzev8T5n+WC0AK4IwEzNYuFaDTWTnNT+F+9VRZgxkGvcDRBEvsyvFOGcH7sRxbsKnpPdGhUrj2lrP6s/gHHqWOGBFzfrgAak0XhSbr4nqSdlOOExz73SYAZG+2oN2B01NC9eV7MAiZWJTVzkA4PtyTF8CoeGXGfqf5dOvr7xKOl5xr8A59JyLCW2lTbqEXS2g5cYQJdIr8vzqcWj0iXw4r1IMAgSQQKFVyxdL/zfDvMq25qr0fe1RyeGGHEl7DrXd5RJZkXRyrZwZqzdTRoJXuNgyG5rC9nI5RDT0PjLF6gfZlReeT0amt5klLIDA7w+b3DWi0kAYhVX60OXuFcTnLcQ57dlJeGrHpKHfrMfJFI8p1UQmPlMIhZhLyEQOvS3WolhsADLBe6FGAxVFSjFtJmo4Dz7pk9DrL474kAfvkcclN6HcasDAKGK8FcMTQ+/wV2Z4TQPfe5XGdmIlR5CnX2L84lNGSpLvXSLdIJpYjifYj7yd4iJ6WqfV8ACjfi8nD5u+IhsZy4ntwtCr9H7iXnmztiyrW7EfVPVyQiqq7T7ShKS8tYIKrP9Tjebqi2o4Dr9oC9rYwrRrDdUsXaaqfgm6Bfj6mUo3Q+hpG0f29QXr8HAaptO+fsAT+e2htKVYqKLN/nDbQkIL7zXWZXUonv9xfzbGJN0BgLqJddClypPSVbEFN5ugqxETq4bmDrb+706Waig9ZpMEz6fD5ViSYYnICKwEQv64NXuSBrA2GHx6RBH1UkHjEGMBACgVTrLSrwlmwUY0WxJkHQNWhwImIRnaksxTl502lExVsyrub/L8zqlFtfOr21K4x6/XsfE7p7tqfPep/Eny5wV16pRpSB+oUyU/VIe4Uj976o5AE4fK2B4qqcIOyUgASqJich5c46C7pBFxwG6N3Aa6a2suU6JaFnaTvSSjLenAz49fQW17z7IMVRtguTOrwGTD8QI6EiHtjbVM1ibSYW2ZrD1KnMYa2hF4XWpH2kCTV5cuRHfZ7gMkeAz4Zyx+zdwSm83K2T+svJoihPCbs6POonhRnm7nAmKFTfZMitYpIA/cadStcPTjCMGtN1W8kbDTKcY5/Dr8kqAR7BUt7+4ubB4pIbhRfBM1GX+FAKwDrZ+hNFE2Mjpf5V0pBMzoLgfd665pXQBAsoqshBhgoHLy+8Pzo/HnthtBbUZ39/aURh5kdp45PA67aXSBosPucZ7W76xCV3mYN3wstdFcJaI1N99uTTldREJN9o3RNSZ/Vtyjyzm49PBhE+n3TCHjkGuybQOYQpNkCDwEWX7N5s4zk86VHv9da1l4z/QPesAorzK0Y38oKl13V7/mtwP9US+QWsq3Ojly6bcam/FJAdLsp1p0uMWSelfrO3Gh4SlWRT6wUTN1p4bu1GnOB+35dQDJbnDuzYqgJDVBAFyItbBuXFihE2z9DW6gFJNvCR9zku+TdjxJtXqyXhqNOEx3NAOfneZWbHo3N5reM+0OTGJcnsZTd3V/voQUHJPkCNpk2sdv4jbRKvu8FRsAm+6sGYDg3stl5Z6XZHhoF3AfliQbNlFLEABXhNy0+BYyoVN+KCFb8/E8b+KneA6XHBw3UVvkQKxJeraLUbVeKgWMPXXkM0MCh0pXa5rviO1TutzQ+OTRu66+Q1QrrsIqnJdtRE3zTpzdQGQeztSrG+6p1u71v6VrOJASSLfirAEOuk/0lY0+V6BeUEU/GkmfDMchGIKkC6u6JQpgyHbveiyEf2LrjQzQbxKAYTpFcjOWhfAAqbITHDmgLQxdvkHz3OwJsoC3zyUKZ/R4g3tDu2Vjq0kjP5wfM3zO86bkPHO/BWpkyIw5AFzyW/8FhXMOhorWqwZaCwgchATdPD4bdvfBiCd4PfkiP19jhpR3KyTPDCXk/Rp/emdC2PvUWKMANXtDVZQ+n50gwctUYLc4E9CQFDjLqe/nBhDLfflcKsZQBvGPXNSSYZnejaMHo1lYH5UjtigxA/QkbpnaHlwwRLtfq4oaaFb0ECUdgBTN+Q5Mel1mUinOniLiMwLzRuk2Lp1wDnUU4nJ/of45zBhM5EON5YVLuHC9htpHgOGkgovCQ9V6N/plklqnMvbCO6k7Am0oGc61KbuZ0kCiJybOUECv/CNMyqXa9DdI+KrciTXN1B9jNK8nDiMbZhli489kk/PdOpLYa7O6o7qsEpAvDt4XEfyRLhD/WrgbLLwHljfAIfj4tyCjjUvBP7GK17EPOuDnrkT3CNTHeGSxSfPUzTRwVG4lk9b9zRuuBFZXK+35Ld+7cAol8uFctu/Sg8qCYaOyahzojrXYj1hryj/K93IUmJWbj8n5I+luRC8A8y1C8JcxWIIS1OR8fhx0O6nzWw/Uj4FJ4QI2pxg2bukGqHEkSNmwNcTePB0mdAKS5DafdGzxNnORULvzashfYbbmlkEBkJE+lyEAF2oXuv
  global:
    GITHUB_USER_PASSWORD:
      secure: E+YdBdg3dqm5vZl25Ug5KYfa2M5I3/LdtVR/UtV9HZT1EEkrsQPFd9MQdxg/pbtE

  matrix:
    - TYPE: Release
    - TYPE: Debug

install:
  - cmd: >-
      $fileContent = "-----BEGIN OPENSSH PRIVATE KEY-----`n"

      $fileContent += $env:priv_key.Replace(' ', "`n")

      $fileContent += "`n-----END OPENSSH PRIVATE KEY-----`n"

      Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent

      git submodule -q update --init --recursive
  # Python 3
  - cmd: set PATH=C:\Python-x64;C:\Python-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

build_script:
  - cmd: cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=%TYPE%
  - cmd: cmake --build _builds --config %TYPE%

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - /^pr\..*/