name: Upload
on: [push]

jobs:
  build:
    strategy:
      matrix:
        type: [Release]
    name: hunter
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: python
        run: |
          python --version
          pip install --upgrade pip
          pip install requests
          pip install gitpython
      - name: upload
        run: |
          cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=${{ matrix.type }}
          cmake --build _builds --config ${{ matrix.type }}
        env:
          GITHUB_USER_PASSWORD: ${{ secrets.hunter }}
