name: Upload
on: [push]

jobs:
  build:
    name: hunter
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: prepare environment
        run: sudo apt install git &&
             git submodule update --init

      - name: python
        run: |
          python --version
          pip install --upgrade pip
          pip install requests
          pip install gitpython
          pip list

      - name: upload
        run: |
          cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Release
          cmake --build _builds --config Release
        env:
          GITHUB_USER_PASSWORD: RIrLXm/iw/gOK/mJ7m1Z1uDln9/aUqtIOKqMI0H0UlgkkIdRa2O7NeQ575F7Erm4

      - name: upload2
        run: |
          cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Debug
          cmake --build _builds --config Debug
        env:
          GITHUB_USER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}