name: Upload
on: [push]

jobs:
  build:
    name: hunter
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: prepare environment
        run: sudo apt install git &&
             git submodule update --init

      - name: python
        run: |
          python --version
          pip install --upgrade pip
          pip install requests
          pip install gitpython
          pip list

      - name: upload
        run: |
          cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Release
          cmake --build _builds --config Release
        env:
          GITHUB_USER_PASSWORD: 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

      - name: upload2
        run: |
          cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Debug
          cmake --build _builds --config Debug
        env:
          GITHUB_USER_PASSWORD: qGJ+1HNJV6ui0bH1F7bZ1f+bmXPesdzGa2iWclyohd3O9jwyRwbh63wfl0i/prS6