name: Upload
on: [push]

jobs:
  build:
    strategy:
      matrix:
        type: [Release, Debug]
    name: hunter
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: python
        run: |
          python --version
          pip install --upgrade pip
          pip install requests
          pip install gitpython

      - name: upload
        run: |
          cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=${{ matrix.type }}
          cmake --build _builds --config ${{ matrix.type }}
        env:
          GITHUB_USER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
#E+YdBdg3dqm5vZl25Ug5KYfa2M5I3/LdtVR/UtV9HZT1EEkrsQPFd9MQdxg/pbtE
      - name: check
        run: |
          cd _builds
          ls

      - name: check2
        run: |
          cd /home/runner/.hunter/_Base/Cache
          ls
          cd raw
          ls

      #- name: upload2
      #  run: |
      #    cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Debug
      #    cmake --build _builds --config Debug
      #  with:
      #    GITHUB_USER_PASSWORD: E+YdBdg3dqm5vZl25Ug5KYfa2M5I3/LdtVR/UtV9HZT1EEkrsQPFd9MQdxg/pbtE